[build]
  command = "npm run build"  # Der Befehl zum Bauen deiner Anwendung
  publish = "dist"  # Das Verzeichnis, das nach dem Build veröffentlicht wird

[context.production.environment]
  NODE_ENV = "production"  # Setzt die Umgebungsvariable für Produktion

  # Beispiel für Go, wenn du es benötigst:
  GO_VERSION = "1.19"  # Gibt die Go-Version für Netlify an

[[redirects]]
  from = "/old-url"
  to = "/new-url"
  status = 301
  force = true
